### ISSUE TITLE
Shops and Licenses

### ISSUE THREAD

**Issue by studioforty9-dev** [shyim/store-plugin-installer#1]
Shops are only setup on the Merchant's Shopware Account. As an Agency, we don't have the username/password of the Merchant even though their domain is linked to our Shopware account under "Licenses" and we can view/download the purchased plugins.

Is there any way to change the code so it retrieves Licenses rather than Shops from our "linked" Shopware account.

thanks,

Alan.

**Comment by shyim** [comment]
Has been fixed with https://github.com/shyim/store-plugin-installer/commit/baf6571d2e57115a4f38790f4b553b51270936a7
