### ISSUE TITLE
[ErrorException]     ZipArchive::statIndex(): Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by Forestsoft-de** [shyim/store-plugin-installer#11]
In PluginInstaller Class Method extractPlugin
ZipArchive should be checked if its readable and should throw a useful error message.

Thanks a lot.

**Comment by Forestsoft-de** [comment]
In my Case the zip file is incomplete:

![image](https://user-images.githubusercontent.com/132578/50643933-b3923200-0f6f-11e9-9d55-f6b6e0d44aa9.png)

The File is incomplete because the test period of the plugin is overdue. :)

**Comment by shyim** [comment]
Nice Hint Thanks. I will look

**Comment by Forestsoft-de** [comment]
#14 we have a big pain on this issue :) here is my pr. would be great to merge :)

**Comment by shyim** [comment]
Thanks :)
