### ISSUE TITLE
FR: Support simple version number constraints

### ISSUE THREAD

**Issue by RobertLang** [shyim/store-plugin-installer#15]
It would be great if the plugin could support simple version number constraints like 3.*

I know this could lead to the use of unspecific plugin versions. Our use case would be to use wildcard version numbers to check the latest version of a plugin during development but to narrow down to an exact version for production/staging.

Example:
```
"extra": {
        "plugins": {
            "dev": {
                "SwagPromotion": "3.*",
                "SwagFuzzy": "3.2.*"
            },
            "production": {
                "SwagPromotion": "3.0.0",
                "SwagFuzzy": "3.2.1"
            }
        }
    },
```

**Comment by mitelg** [comment]
should be easy to find the maximum allowed version, as you already use composer components
