### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by studioforty9-dev** [shyim/store-plugin-installer#20]
Getting the following error when running composer update:

`[Installer] Fetching shop licenses failed with code "PluginLicensesException-8"  
  ! `

The login details work fine to login to the account in a browser. Just wondering if anything has changed with the API like the last time.

**Comment by shyim** [comment]
Today was an update on Shopware Account API. I have already notified the corresponding team, about the issue

**Comment by shyim** [comment]
Can you change the following line https://github.com/shyim/store-plugin-installer/blob/master/src/Shyim/Api/Client.php#L163

to 
```
if (!empty($partnerAccount['partnerId'])) {
```

**Comment by shyim** [comment]
Should be fixed with the new version
