### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by josh1va** [shyim/store-plugin-installer#22]
Hi,

since shortly we have the following issue running `composer install`  and `composer update`:

>  [InvalidArgumentException]                                                                                  
>   Could not download plugin XY in version X.Y.Z maybe not a valid licence for this version 

Stacktrace:

> Exception trace:
>  () at/home/dev/project/mieb//vendor/shyim/store-plugin-installer/src/Shyim/PluginInstaller.php:94
>  Shyim\PluginInstaller->movePlugin() at/home/dev/project/mieb//vendor/shyim/store-plugin-installer/src/Shyim/PluginInstaller.php:79
>  Shyim\PluginInstaller->installPlugin() at/home/dev/project/mieb//vendor/shyim/store-plugin-installer/src/Shyim/ComposerPlugin.php:82
>  Shyim\ComposerPlugin::installPlugins() at n/a:n/a
>  call_user_func() at phar:///home/dev/composer//bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:176
>  Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///home/dev/composer//bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
>  Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///home/dev/composer//bin/composer.phar/src/Composer/Installer.php:323
>  Composer\Installer->run() at phar:///home/dev/composer//bin/composer.phar/src/Composer/Command/InstallCommand.php:121
>  Composer\Command\InstallCommand->execute() at phar:///home/dev/composer//bin/composer.phar/vendor/symfony/console/Command/Command.php:241
>  Symfony\Component\Console\Command\Command->run() at phar:///home/dev/composer//bin/composer.phar/vendor/symfony/console/Application.php:843
>  Symfony\Component\Console\Application->doRunCommand() at phar:///home/dev/composer//bin/composer.phar/vendor/symfony/console/Application.php:193
>  Symfony\Component\Console\Application->doRun() at phar:///home/dev/composer//bin/composer.phar/src/Composer/Console/Application.php:254
>  Composer\Console\Application->doRun() at phar:///home/dev/composer//bin/composer.phar/vendor/symfony/console/Application.php:117
>  Symfony\Component\Console\Application->run() at phar:///home/dev/composer//bin/composer.phar/src/Composer/Console/Application.php:103
>  Composer\Console\Application->run() at phar:///home/dev/composer//bin/composer.phar/bin/composer:56
>  require() at /home/dev/composer//bin/composer.phar:24

Do you know if the shopware store api has changed recently which causes the error? It just works perfectly last week .

We have no license issues with the Webstore on https://store.shopware.com or via /backend.

Thanks in advance! 

Best regards, 
Josh

**Comment by p-anders** [comment]
We currently have the same issue on a customer project:

As far Ive debugged, the plugin download on https://api.shopware.com/plugins/XXXXX/binaries/XXX/file throws a `Unauthorized` error:

```
array(2) {
  ["success"]=>
  bool(false)
  ["code"]=>
  string(16) "UsersException-4"
}
```

**Comment by shyim** [comment]
Every second week Monday is a release of the Account infrastructure :see_no_evil: 
This time they changed authentication from query string to header and changed the response. :see_no_evil:

**Comment by studioforty9-dev** [comment]
Thanks. Can we get a new version number - 0.2.5 :)

**Comment by josh1va** [comment]
Thank you very much @shyim !

**Comment by shyim** [comment]
Have tagged a new version
