### ISSUE TITLE
Latest Version and Plugin Code versus Name

### ISSUE THREAD

**Issue by studioforty9-dev** [shyim/store-plugin-installer#5]
This works great now - thanks :)

Is there anyway to just install the latest version of the plugin or for it to at least notify the developer on install that a newer version is available? 

Also, when viewing a plugin in my Shopware Account, I'm actually seeing the Plugin "Code" rather than the Name. For example, "Shopware Storytelling" plugin shows the code "Swag986953104487". Nowhere does it show the Plugin name that's required for composer installation (i.e., "SwagEmotionAdvanced"). I needed to var_dump the API response to discover this.

**Comment by shyim** [comment]
Hey,
i have added installing by code. I will show later with the notification, because i want to notify only **valid** updates for the used shopware version

**Comment by shyim** [comment]
Has been fixed in the meantime

**Comment by Forestsoft-de** [comment]
I think it doesnt Work SwagPaypal;

 Plugin with name "Swag828732772311f" is not available in your Account. Please buy the plugin first

**Comment by shyim** [comment]
Is the paypal plugin bought for the domain?

**Comment by Forestsoft-de** [comment]
after debugging i found out that is called SwagPaymentPayPalUnified. What a mess :)

**Comment by shyim** [comment]
Normally the install code should also work as see in this Test https://github.com/shyim/store-plugin-installer/blob/master/tests/PluginInstallTest.php#L79

**Comment by Forestsoft-de** [comment]
Thats correct now i see the mistake. There is a typo in shopware account:

![image](https://user-images.githubusercontent.com/132578/50294103-701acc80-0475-11e9-8bbb-356e36620052.png)

Every code has an f as suffix. The Link to the search is without the f.

can be closed.
