### ISSUE TITLE
Wildcard Umgebung

### ISSUE THREAD

**Issue by bragento** [shyim/store-plugin-installer#6]
Hey there seems an issue with Wildcard Account. In our Store Backend I have configured the following Site.

![bildschirmfoto 2018-09-06 um 15 30 08](https://user-images.githubusercontent.com/4529135/45160747-7d73ba00-b1ea-11e8-968b-3a6d7ac66f44.png)

On the given Server in our Docker Enviroment I getting this Error:

![bildschirmfoto 2018-09-06 um 15 32 57](https://user-images.githubusercontent.com/4529135/45160899-de9b8d80-b1ea-11e8-97b0-1f1ced0d8bba.png)

That's the interesting part of composer.json 

`"extra": {
    "installer-paths": {
      "Plugins/Local/Backend/{$name}/": [
        "type:shopware-backend-plugin"
      ],
      "Plugins/Local/Core/{$name}/": [
        "type:shopware-core-plugin"
      ],
      "Plugins/Local/Frontend/{$name}/": [
        "type:shopware-frontend-plugin"
      ]
    },
    "plugins":{
      "production":{
        "SwagCustomProducts": "4.2.0"
      }
    }
  },`

**Comment by shyim** [comment]
Hey @bragento,
unfortunately the Wildcard API does not support plugin versions, so there is no way to integrate this project.

I will try to create a internal ticket for that
